---

- name: Disable swap
  shell: /usr/sbin/swapoff -a

- name: Disable swap fstab
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

- name: install k3s service file
  template:
    src: "k3s.service-node.j2"
    dest: "/etc/systemd/system/k3s.service"
    owner: root
    group: root
    mode: 0755

- name: enable k3s daemon
  systemd:
    name: k3s
    daemon_reload: yes
    state: restarted
    enabled: yes
